//
// Generated by CNCC MLISA Back-End
//

.mlisa 2.0
.arch MLU270
.stack nram

// .globl	_Z12gemm16KernelPDhPaS0_jjjs
.nram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM[65536];
.nram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM[65536];
.nram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp[65536];
.wram .align 64 .b8  .len 65536 _ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM[65536];
.nram .align 64 .b8  .len 131072 _ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM[131072];
.sram .align 1 .b8  .len 262144 _ZZ12gemm16KernelPDhPaS0_jjjsE11input2SRAM1[262144];
.sram .align 1 .b8  .len 262144 _ZZ12gemm16KernelPDhPaS0_jjjsE11input2SRAM2[262144];
.sram .align 32 .ptr _ZZ12gemm16KernelPDhPaS0_jjjsE15input2SRAM_read;
.sram .align 32 .ptr _ZZ12gemm16KernelPDhPaS0_jjjsE16input2SRAM_write;

.visible .kernel _Z12gemm16KernelPtPaS0_jjjs(
	.arg .ptr _Z12gemm16KernelPDhPaS0_jjjs_arg_0,
	.arg .ptr _Z12gemm16KernelPDhPaS0_jjjs_arg_1,
	.arg .ptr _Z12gemm16KernelPDhPaS0_jjjs_arg_2,
	.arg .s32 _Z12gemm16KernelPDhPaS0_jjjs_arg_3,
	.arg .s32 _Z12gemm16KernelPDhPaS0_jjjs_arg_4,
	.arg .s32 _Z12gemm16KernelPDhPaS0_jjjs_arg_5,
	.arg .s16 _Z12gemm16KernelPDhPaS0_jjjs_arg_6
)
{
	.gpr 	%ZERO;
	.sreg	%clusterdim, %clusterid, %coredim, %coreid, %taskdim, %taskid;
	.gpr 	%r<113>;

	ld.gpr.arg 	%r34, _Z12gemm16KernelPDhPaS0_jjjs_arg_5, 4;
	ld.gpr.arg 	%r33, _Z12gemm16KernelPDhPaS0_jjjs_arg_4, 4;
	ld.gpr.arg 	%r32, _Z12gemm16KernelPDhPaS0_jjjs_arg_3, 4;
	ld.gpr.arg 	%r31, _Z12gemm16KernelPDhPaS0_jjjs_arg_2, 6;
	ld.gpr.arg 	%r36, _Z12gemm16KernelPDhPaS0_jjjs_arg_1, 6;
	mul.gpr.s32 	%r37, %r33, %r32;
	lda.gpr.nram 	%r38, _ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM;
	ld.nram.gdram 	[%r38], [%r36], %r37;
	mv.gpr.sreg 	%r0, %taskdim;
	sll.gpr.u32 	%r39, %r0, 0x8;
	div.gpr.u32 	%r1, %r34, %r39;
	lda.gpr.sram 	%r41, _ZZ12gemm16KernelPDhPaS0_jjjsE11input2SRAM1;
	st.sram.gpr 	_ZZ12gemm16KernelPDhPaS0_jjjsE16input2SRAM_write, %r41, 6;
	mv.gpr.sreg 	%r4, %clusterid;
	sll.gpr.u32 	%r5, %r33, 0xa;
	mul.gpr.s32 	%r42, %r5, %r4;
	add.gpr.ptr	%r43, %r42, 0;
	add.gpr.ptr	%r44, %r31, %r43;
	ld.sram.gdram 	[%r41], [%r44], %r5;
	mv.gpr.sreg 	%r6, %clusterdim;
	beq.gpr.s32 	LBB0_2, %r6, 0;
	mv.gpr.sreg 	%r46, %coredim;
	add.gpr.s32 	%r45, %r46, 1;
	.volatile {
	//
	barrier.sync.local 1, %r45;
	
	//
	}
LBB0_2:
	sll.gpr.u32 	%r2, %r33, 0x8;
	add.gpr.s32 	%r47, %ZERO, 1;
	blt.gpr.s32 	LBB0_5, %r47, %r1;
	jmp 	LBB0_3;
LBB0_5:
	sll.gpr.u32 	%r40, %r33, 0x2;
	ld.gpr.arg 	%r35, _Z12gemm16KernelPDhPaS0_jjjs_arg_6, 2;
	ld.gpr.arg 	%r30, _Z12gemm16KernelPDhPaS0_jjjs_arg_0, 6;
	and.gpr.u32 	%r3, %r40, 0x3fffffc;
	add.gpr.s32 	%r51, %r1, -1;
	sll.gpr.u32 	%r8, %r4, 0x2;
	sll.gpr.u32 	%r52, %r33, 0x6;
	cvti32.gpr.tz.s16 	%r9, %r35;
	cvti48.gpr.tz.s32 	%r10, %r51;
	add.gpr.ptr	%r53, %r33, 0;
	lda.gpr.nram 	%r54, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM;
	add.gpr.ptr	%r11, %r54, %r53;
	add.gpr.ptr	%r55, %r52, 0;
	lda.gpr.nram 	%r56, _ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp;
	add.gpr.ptr	%r12, %r56, %r55;
	sll.gpr.u32 	%r57, %r33, 0x1;
	add.gpr.ptr	%r58, %r57, 0;
	add.gpr.ptr	%r13, %r54, %r58;
	sll.gpr.u32 	%r59, %r33, 0x7;
	add.gpr.ptr	%r60, %r59, 0;
	add.gpr.ptr	%r14, %r56, %r60;
	mul.gpr.s32 	%r61, %r33, 3;
	add.gpr.ptr	%r62, %r61, 0;
	add.gpr.ptr	%r15, %r54, %r62;
	mul.gpr.s32 	%r63, %r33, 192;
	add.gpr.ptr	%r64, %r63, 0;
	add.gpr.ptr	%r16, %r56, %r64;
	add.gpr.ptr	%r17, %r32, 0;
	add.gpr.ptr 	%r107, %ZERO, 0x000000000000;
	lda.gpr.sram 	%r67, _ZZ12gemm16KernelPDhPaS0_jjjsE11input2SRAM2;
	mv.gpr.sreg 	%r78, %coreid;
	mul.gpr.s32 	%r79, %r2, %r78;
	add.gpr.ptr	%r106, %r79, 0;
	mv.gpr.gpr 	%r101, %r10;
	mv.gpr.sreg 	%r100, %coredim;
	add.gpr.s32 	%r99, %r100, 1;
	add.gpr.s32 	%r84, %ZERO, 0;
	mv.gpr.sreg 	%r85, %taskid;
	lda.gpr.nram 	%r96, _ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM;
LBB0_6:
	mv.gpr.gpr 	%r20, %r107;
	and.gpr.u32 	%r65, %r20, 0x1;
	eq.gpr.s32 	%r66, %r65, 0;
	mv.gpr.gpr 	%r108, %r41;
	bne.gpr.s32 	LBB0_7, %r66, %ZERO;
	mv.gpr.gpr 	%r108, %r67;
LBB0_7:
	mv.gpr.gpr 	%r109, %r67;
	bne.gpr.s32 	LBB0_8, %r66, %ZERO;
	mv.gpr.gpr 	%r109, %r41;
LBB0_8:
	st.sram.gpr 	_ZZ12gemm16KernelPDhPaS0_jjjsE15input2SRAM_read, %r108, 6;
	st.sram.gpr 	_ZZ12gemm16KernelPDhPaS0_jjjsE16input2SRAM_write, %r109, 6;
	add.gpr.ptr	%r107, %r107, 0x000000000001;
	mv.gpr.gpr 	%r71, %r107;
	mul.gpr.s32 	%r72, %r0, %r71;
	add.gpr.s32 	%r73, %r72, %r8;
	mul.gpr.s32 	%r74, %r2, %r73;
	add.gpr.ptr	%r75, %r74, 0;
	add.gpr.ptr	%r76, %r31, %r75;
	ld.sram.gdram 	[%r109], [%r76], %r5;
	ld.gpr.sram 	%r77, _ZZ12gemm16KernelPDhPaS0_jjjsE15input2SRAM_read, 6;
	add.gpr.ptr	%r80, %r77, %r106;
	ld.nram.sram 	_ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp, [%r80], %r2;
	mv.stride.nram.nram	_ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp, %r33, %r3, %r33, 64;
	mv.stride.nram.nram	[%r11], [%r12], %r33, %r3, %r33, 64;
	mv.stride.nram.nram	[%r13], [%r14], %r33, %r3, %r33, 64;
	mv.stride.nram.nram	[%r15], [%r16], %r33, %r3, %r33, 64;
	mv.wram.nram 	_ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2NRAM, %r2;
	conv.nram.f16fix8fix8	_ZZ12gemm16KernelPDhPaS0_jjjsE10outputNRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input1NRAM, _ZZ12gemm16KernelPDhPaS0_jjjsE10input2WRAM, %r33, %r32, 1, 1, 1, 1, 1, 256, %r9;
	beq.gpr.s32 	LBB0_11, %r32, 0;
	jmp 	LBB0_14;
LBB0_14:
	mul.gpr.s32 	%r23, %r0, %r20;
	mv.gpr.gpr 	%r110, %r17;
	mv.gpr.gpr 	%r111, %r84;
	mv.gpr.gpr 	%r112, %r84;
LBB0_15:
	add.gpr.s32 	%r86, %r85, %r23;
	sll.gpr.u32 	%r87, %r86, 0x8;
	cvti48.gpr.tz.s32 	%r88, %r87;
	sll.gpr.ptr 	%r89, %r88, 0x1;
	add.gpr.ptr	%r90, %r30, %r89;
	add.gpr.ptr	%r91, %r111, 0;
	sll.gpr.ptr 	%r92, %r91, 0x1;
	add.gpr.ptr	%r93, %r90, %r92;
	cvti48.gpr.tz.s32 	%r94, %r112;
	sll.gpr.ptr 	%r95, %r94, 0x1;
	add.gpr.ptr	%r97, %r96, %r95;
	st.gdram.nram 	[%r93], [%r97], 512;
	add.gpr.s32 	%r112, %r112, 256;
	add.gpr.s32 	%r111, %r111, %r34;
	sub.gpr.ptr	%r110, %r110, 0x000000000001;
	bne.gpr.s32 	LBB0_15, %r110, 0;
LBB0_11:
	beq.gpr.s32 	LBB0_13, %r6, 0;
	.volatile {
	//
	barrier.sync.local 1, %r99;
	
	//
	}
LBB0_13:
	blt.gpr.s32 	LBB0_6, %r71, %r101;
	jmp 	LBB0_4;
LBB0_3:
	mv.gpr.sreg 	%r48, %coreid;
	mul.gpr.s32 	%r49, %r2, %r48;
	add.gpr.ptr	%r106, %r49, 0;
LBB0_4:
	ld.gpr.sram 	%r103, _ZZ12gemm16KernelPDhPaS0_jjjsE16input2SRAM_write, 6;
	add.gpr.ptr	%r104, %r103, %r106;
	ld.nram.sram 	_ZZ12gemm16KernelPDhPaS0_jjjsE14input2NRAM_tmp, [%r104], %r2;
	exit;
}


